CXX = g++
CXXFLAGS = -std=c++11 $(shell pkg-config --cflags opencv4)
LDFLAGS = $(shell pkg-config --libs opencv4)

TARGET = test
SIMPLE_TARGET = simple_test
BASIC_TARGET = basic_test
WEBCAM_TARGET = webcam_test
FACE_TARGET = face_detection_webcam
POSE_TARGET = pose_detection_webcam
ADVANCED_POSE_TARGET = advanced_pose_webcam
DYNAMIC_POSE_TARGET = dynamic_pose_webcam
REAL_POSE_TARGET = real_pose_webcam
SOURCE = test.cpp
SIMPLE_SOURCE = simple_test.cpp
BASIC_SOURCE = basic_test.cpp
WEBCAM_SOURCE = webcam_test.cpp
FACE_SOURCE = face_detection_webcam.cpp
POSE_SOURCE = pose_detection_webcam.cpp
ADVANCED_POSE_SOURCE = advanced_pose_webcam.cpp
DYNAMIC_POSE_SOURCE = dynamic_pose_webcam.cpp
REAL_POSE_SOURCE = real_pose_webcam.cpp

$(TARGET): $(SOURCE)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(SOURCE) $(LDFLAGS)

$(SIMPLE_TARGET): $(SIMPLE_SOURCE)
	$(CXX) $(CXXFLAGS) -o $(SIMPLE_TARGET) $(SIMPLE_SOURCE) $(LDFLAGS)

$(BASIC_TARGET): $(BASIC_SOURCE)
	$(CXX) $(CXXFLAGS) -o $(BASIC_TARGET) $(BASIC_SOURCE) $(LDFLAGS)

$(WEBCAM_TARGET): $(WEBCAM_SOURCE)
	$(CXX) $(CXXFLAGS) -o $(WEBCAM_TARGET) $(WEBCAM_SOURCE) $(LDFLAGS)

$(FACE_TARGET): $(FACE_SOURCE)
	$(CXX) $(CXXFLAGS) -o $(FACE_TARGET) $(FACE_SOURCE) $(LDFLAGS)

$(POSE_TARGET): $(POSE_SOURCE)
	$(CXX) $(CXXFLAGS) -o $(POSE_TARGET) $(POSE_SOURCE) $(LDFLAGS)

$(ADVANCED_POSE_TARGET): $(ADVANCED_POSE_SOURCE)
	$(CXX) $(CXXFLAGS) -o $(ADVANCED_POSE_TARGET) $(ADVANCED_POSE_SOURCE) $(LDFLAGS)

$(DYNAMIC_POSE_TARGET): $(DYNAMIC_POSE_SOURCE)
	$(CXX) $(CXXFLAGS) -o $(DYNAMIC_POSE_TARGET) $(DYNAMIC_POSE_SOURCE) $(LDFLAGS)

$(REAL_POSE_TARGET): $(REAL_POSE_SOURCE)
	$(CXX) $(CXXFLAGS) -o $(REAL_POSE_TARGET) $(REAL_POSE_SOURCE) $(LDFLAGS)

all: $(TARGET) $(SIMPLE_TARGET) $(BASIC_TARGET) $(WEBCAM_TARGET) $(FACE_TARGET) $(POSE_TARGET) $(ADVANCED_POSE_TARGET) $(DYNAMIC_POSE_TARGET) $(REAL_POSE_TARGET)

clean:
	rm -f $(TARGET) $(SIMPLE_TARGET) $(BASIC_TARGET) $(WEBCAM_TARGET) $(FACE_TARGET) $(POSE_TARGET) $(ADVANCED_POSE_TARGET) $(DYNAMIC_POSE_TARGET) $(REAL_POSE_TARGET)

.PHONY: clean all 